name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
          java-version: 8
          distribution: temurin

    - name: Mount caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{matrix.scala}}-${{ hashFiles('**/*.sbt') }}

    - name: Formatting
      run: |
        sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck

    - name: Compile and test
      run: |
        sbt +test

    - name: Examples
      run: |
        cd example && sbt compile

  # Single final job for mergify.
  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: ':'
